@powershell -NoProfile -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"
@powershell -NoProfile -ExecutionPolicy Bypass -Command "choco install jdk8 -y"
@powershell -NoProfile -ExecutionPolicy Bypass -Command "choco install notepadplusplus.install -y"
@powershell -NoProfile -ExecutionPolicy Bypass -Command "choco install tortoisesvn -y"
@powershell -NoProfile -ExecutionPolicy Bypass -Command "choco install git.install -y"
@powershell -NoProfile -ExecutionPolicy Bypass -Command "choco install tortoisegit -y"
@powershell -NoProfile -ExecutionPolicy Bypass -Command "choco install visualstudiocode -y"
@powershell -NoProfile -ExecutionPolicy Bypass -Command "choco install winmerge -y"
@powershell -NoProfile -ExecutionPolicy Bypass -Command "choco install maven -y"
@powershell -NoProfile -ExecutionPolicy Bypass -Command "choco install sublimetext3 -y"
@powershell -NoProfile -ExecutionPolicy Bypass -Command "choco install ant -y"
@powershell -NoProfile -ExecutionPolicy Bypass -Command "choco install putty.install -y"
@powershell -NoProfile -ExecutionPolicy Bypass -Command "choco install nodejs.install -y"
@powershell -NoProfile -ExecutionPolicy Bypass -Command "choco install 7zip -y"
@powershell -NoProfile -ExecutionPolicy Bypass -Command "choco install filezilla -y"
